steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/parabolic-hook-436014-d0/npmjs-clone', '.']
  
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/parabolic-hook-436014-d0/npmjs-clone']
  
  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'npmjs-clone',
           '--image', 'gcr.io/parabolic-hook-436014-d0/npmjs-clone',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']

images:
  - 'gcr.io/parabolic-hook-436014-d0/npmjs-clone'